name: flutter_first_app
description: The first Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:

  sdk: ">=2.17.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3

  # ローカライゼーション
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter:

  uses-material-design: true

  # ローカライゼーション
  generate: true
